# TODO: Test with different py versions using sub workflows
image: python:3.10

stages:
  - test
  - lint
  - bump
  - version
  - build
  - release
  - deploy

workflow:
  rules:
      # Prevent running a push pipeline for a release commit that's not a tag
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\):.*/ && $CI_COMMIT_TAG == null
      when: never
      # Prevent merge request pipelines
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
      # We run CI on our own servers from the master repo
    - if: $CI_SERVER_HOST == "gitlab.com"
      when: never
    - when: always


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# Default cache values
default:
  cache: &global_cache
    key: 'main'
    paths:
      - .cache/pypoetry
      - .cache/pip
      - .venv/
    policy: pull-push


# Anchor to use pull only cache
.use_cached_venv: &use_cached_venv
  before_script:
    - source .venv/bin/activate
  cache:
    <<: *global_cache
    policy: pull


.only_tag: &only_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never


.no_tag: &no_tag
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: on_success


.only_protected: &only_protected
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG == null
      when: on_success
    - when: never


# Anchor for docker jobs
.docker-job:
  image: docker:latest
  services:
    - docker:dind
  # Deactivate cache for docker jobs
  cache: []

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REPO_URL: "https://release-token:${RELEASE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"


# Setup job to install dependencies
build-env:
  stage: .pre
  script:
    - python -m venv .venv/
    - source .venv/bin/activate
    - pip install -U pip
    - pip install poetry
    - poetry install
  rules:
      # If project dependencies were changed then run
    - changes:
      - pyproject.toml
      - manifest/
      when: always
      # If .venv exists then skip
    - exists:       
      - .venv/
      when: never
    # Default to manual, but continue
    # pipeline if not run
    - when: manual
      allow_failure: true


unit-tests:
  <<: *use_cached_venv
  <<: *no_tag
  stage: test
  script:
    - make test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
    paths:
      - coverage-report/


lint:
  <<: *use_cached_venv
  <<: *no_tag
  stage: lint
  script:
    - make lint


bump-version:
  <<: *use_cached_venv
  <<: *only_protected
  stage: bump
  before_script:
      # Install semantic-release, not sure why it's not in the venv already
    - pip install python-semantic-release
      # Set git info
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_USER"
      # NOTE: Must be set to CLONE strategy in gitlab CI otherwise there will be
      # excess commits and tags from a dirty cache
    - git checkout $CI_COMMIT_BRANCH
    - git pull $REPO_URL $CI_COMMIT_BRANCH
      # Explicitly checkout branch since gitlab CI detaches
  script:
    # Bump the version with prerelease tag
    - export DID_BUMP=$(semantic-release version 2>&1)
    # Push new tag to trigger release workflow if bumped
    - echo $DID_BUMP
    - |
      if [[ $DID_BUMP == *"No release will be made."* ]]; then
        echo "Semantic release did not bump the version"
      else
        echo "Semantic release bumped the version"
        git push $REPO_URL $CI_COMMIT_BRANCH --tags
      fi


get-version:
  <<: *use_cached_venv
  <<: *only_tag
  stage: version
  script:
    # Create release.env
    - echo "VERSION=$(poetry version --short)" >> release.env
    # Ensure the file is formatted correctly
    - cat release.env
  artifacts:
    reports:
      dotenv: release.env


build-docs:
  <<: *use_cached_venv
  <<: *only_tag
  stage: build
  script:
    - make docs
  artifacts:
    paths:
      - site/
    expire_in: 1 week


build-docs-docker:
  <<: *only_tag
  extends: .docker-job
  stage: build
  needs:
    - job: get-version
      artifacts: true
    - job: build-docs
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:docs-latest" -t "$CI_REGISTRY_IMAGE:docs-$VERSION" -f docker/docs.Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE" --all-tags


build-wheel:
  <<: *use_cached_venv
  <<: *only_tag
  stage: build
  script:
    # Build the wheel
    - poetry build --format wheel
  artifacts:
    name: dist
    paths:
      - dist/


make-release:
  <<: *use_cached_venv
  <<: *only_tag
  stage: release
  needs:
    - job: get-version
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Building release $VERSION"
  release:
    name: Release $VERSION
    tag_name: $VERSION
    description: $CHANGELOG


publish-wheel:
  <<: *use_cached_venv
  <<: *only_tag
  stage: release
  script: |
      # Publish the built wheel to the registry
      poetry config pypi-token.pypi $PYPI_TOKEN
      poetry publish


deploy-docs:
  <<: *only_tag
  extends: .docker-job
  stage: deploy
  needs:
    - job: get-version
      artifacts: true
    - job: build-docs-docker
  script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_TOKEN" $CI_REGISTRY
    - docker stack deploy -c $DOCS_STACK --prune --with-registry-auth $STACK_NAME
  environment:
    name: documentation
    url: https://docs.emergentmethods.ai/$CI_PROJECT_NAME/
  variables:
    DEPLOY_HOST: docs.emergentmethods.ai
    STACK_NAME: $CI_PROJECT_NAME-docs