repos:
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        exclude: ^(tests/docs)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies: [pydantic==1.10.9, types-toml, types-PyYAML]
        exclude: ^(tests|docs)/

  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint