site_name: Manifest
site_description: Modern asynchronous application manifest management toolkit.
site_author: Timothy pogue
copyright: Emergent Methods, LLC
site_url: http://docs.emergentmethods.ai/manifest/
repo_url: https://git.freqai.cloud/wizrds/manifest
repo_name: manifest

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - Basic Usage: basic_usage.md
  - Advanced Usage:
    - advanced_usage/index.md
    - Expressions: advanced_usage/expressions.md
    - Instantiable Objects: advanced_usage/instantiable.md
    - Hooks: advanced_usage/hooks.md
    - Filesystems: advanced_usage/file_systems.md
  - API Reference:
    - Manifest: api/manifest.md
    - Instantiable: api/instantiable.md
    - Expressions: api/expressions.md

extra_css:
  - css/theme.css

theme: 
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - toc.integrate
  icon:
    repo: fontawesome/brands/gitlab
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  palette:
    scheme: slate
    primary: custom
    accent: custom

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
          allow_inspection: false
          show_object_full_path: false
          show_root_heading: false
          show_root_toc_entry: false


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.caret
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true